spring.application.name=consultorio_StaRosa

spring.datasource.url=jdbc:postgresql://localhost:5432/dental_db
spring.datasource.username=admin
spring.datasource.password=Gus123
spring.jpa.hibernate.ddl-auto=update
