spring.application.name=consultorio_StaRosa

spring.datasource.url=jdbc:postgresql://localhost:5432/consultorio_bamban_db
spring.datasource.username=ilseli
spring.datasource.password=Nenita_10
spring.jpa.hibernate.ddl-auto=update